# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f96e99c1c7069c0a0378657057b6512f7c4838155d8a426c86fd8798268662699acdbe3e60215f9a06b856440b653cdb812e510e8224edc4d230d9d07b7acb94

test:
  secret_key_base: ff0645e8fa87c781d69cee7be476235d52d26df158ca0a8a2eee1c19ec81e2526c9ca732a8be444d220f2b2f2cdb7ce75a7efd8729767e14e7464a016238e323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
